name: Wiki CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        DOCKER_REPO=`echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'`;
        DOCKER_TAG=`git rev-parse --short HEAD`;
        docker build . --file Dockerfile --build-arg VCS_REF="$DOCKER_TAG" --tag "docker.pkg.github.com/$DOCKER_REPO/wiki:$DOCKER_TAG"
    - name: Login to Docker Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username beat-saber-modding-group --password-stdin
    - name: Push to Docker Registry
      run: |
        DOCKER_REPO=`echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'`;
        docker push "docker.pkg.github.com/$DOCKER_REPO/wiki"
      if: github.ref == 'refs/heads/master'
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Skip Deploy Wiki Step?
      if: env.ENABLE != 1ENABLED
      run: echo ENABLE_CI_DEPLOY Secret not set to 1, skipping deployment... 

    - name: Checkout git repository
      if: env.ENABLE == 1ENABLED
      uses: actions/checkout@v1
      
    - name: Deploy Wiki
      if: env.ENABLE == 1ENABLED
      run: "curl -X POST -H 'Authorization: Bearer ${{ secrets.HOOK_TOKEN }}' -d `git rev-parse --short HEAD` '${{ secrets.HOOK_URL }}'"
    env:
      ENABLE: ${{ secrets.ENABLE_CI_DEPLOY }}
