# Wiki Update Tracker, to track changes in wiki original pages, and update issues to report when a translation is required

name: Wiki Update Tracker

on:
  push:
    branches: [test-wut]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Skip Tracking Steps?
        if: env.ENABLE != '1ENABLED'
        run: echo ENABLE_WUT Secret not set to 1ENABLED, skipping page tracking... 

      - name: Get custom App JWT
        if: env.ENABLE == '1ENABLED'
        id: get_token
        uses: machine-learning-apps/actions-app-token@0.21
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Checkout git repository
        if: env.ENABLE == '1ENABLED'
        uses: actions/checkout@v2
        with:
          ref: test-wut
          fetch-depth: 0
          token: ${{ steps.get_token.outputs.app_token }}

      - name: Check original pages status and update issues
        if: env.ENABLE == '1ENABLED'
        uses: Awagi/wiki-update-tracker@dev
        with:
          log-level: "DEBUG"
          repo-path: $GITHUB_WORKSPACE
          original: "wiki"
          translations: |
            fr:wiki/fr
            cs:wiki/cs
            de:wiki/de
            zh:wiki/zh
          filters: "**/*"
          ignores: |
            wiki/LICENSE
          gen-stubs: |
            .md
          stub-template: $GITHUB_WORKSPACE/.github/wut-templates/translation-stub-template.md
          gen-copy: |
            *.png
          token: ${{ steps.get_token.outputs.app_token }}
          instruct-projects: |
            *.md
          project-title-template: "Wiki {t.translation.language} Update Tracker"
          project-description-template: "{t.translation.language} translation effort."
          project-card-create-template: $GITHUB_WORKSPACE/.github/wut-templates/project-create-template.md
          project-card-initialize-template: $GITHUB_WORKSPACE/.github/wut-templates/project-initialize-template.md
          project-card-update-template: $GITHUB_WORKSPACE/.github/wut-templates/project-update-template.md
          project-card-uptodate-template: $GITHUB_WORKSPACE/.github/wut-templates/project-uptodate-template.md
          project-card-orphan-template: $GITHUB_WORKSPACE/.github/wut-templates/project-orphan-template.md

    env:
        ENABLE: ${{ secrets.ENABLE_WUT }}
