# Wiki Update Tracker, to track changes in wiki original pages, and update issues to report when a translation is required

name: Wiki Update Tracker

on:
  push:
    branches: [test-wut]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Skip Tracking Steps?
        if: env.ENABLE != 1
        run: echo ENABLE_WUT Secret not set to 1, skipping page tracking... 

      - name: Checkout git repository
        if: env.ENABLE == 1
        uses: actions/checkout@v2
        with:
          ref: test-wut
          fetch-depth: 0

#      - name: Get custom App JWT
#        if: env.ENABLE == 1
#        id: get_token
#        uses: machine-learning-apps/actions-app-token@0.21
#        with:
#          APP_PEM: ${{ secrets.APP_PEM }}
#          APP_ID: ${{ secrets.APP_ID }}

      - name: Check original pages status and update issues
        if: env.ENABLE == 1
        uses: Awagi/wiki-update-tracker@master
        with:
          repo-path: $GITHUB_WORKSPACE
          original-path: "wiki"
          ignored-paths: "wiki/LICENSE,wiki/.vuepress"
          translations: "fr:wiki/fr,de:wiki/de,cs:wiki/cs,zh:wiki/zh"
          file-suffix: ".md"
          bot-label: "WUT"
          token: ${{ secrets.GITHUB_TOKEN }}
          log-level: "DEBUG"
          auto-create: "1"
          update-issues: "1"
          update-projects: "1"
    env:
        ENABLE: ${{ secrets.ENABLE_WUT }}
